# Generated by Django 4.1.1 on 2022-09-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_produto_fotocapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='fotoCapa',
            field=models.ImageField(upload_to=''),
        ),
    ]
