# Generated by Django 4.1.1 on 2022-09-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_produto_fotocapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='fotoCapa',
            field=models.ImageField(height_field='400', upload_to='', width_field='640'),
        ),
    ]
